service: pollapi-service
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: af-south-1

plugins:
  - serverless-domain-manager


custom:
  customDomain:
    domainName: poll.smartdevops.net
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true

functions:
  hello:
    handler: handler.hello
    events:
     - http:
         path: hello
         method: get
  create_poll:
    handler: handler.create_poll
    events:
     - http:
         path: poll
         method: post

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
